name: CI

on:
  # Se ejecutara cuando se haga push
  push:

  # Ajuste que puso por defecto github par aejecutarlo manualmente desde actions
  workflow_dispatch:

# Lo que lleva a cabo la integracion continua
jobs:
  # Este workflow tiene solo un job "tests"
  test:
    # En donde corre
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout del código
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      #- name: Ejecutar pruebas específicas con Maven
      #  run: mvn -Dtest=ConceptMatchingCheckAnswerCommandTest,\
      #                  ConceptMatchingGetDataCommandTest,\
      #                  ConceptMatchingServiceTest,\
      #                  ConceptoDTOTest,\
      #                  ConceptosDefinicionesTOATest,\
      #                  DefinicionDTOTest test
